### ISSUE TITLE
Make possible assertions through lists

### ISSUE THREAD

**Issue by D4nza** [wirewit/restretto#7]
Example 1:

```
[
  {
    "id": 1,
    "name": "foo"
  },
  {
    "id": 2,
    "name": "bar"
  },
]
```

```  
- title: get list of items
    get: /items/
    assert:
      - status: 200
      - body: json
        property: json[0].id
        is: 1
      - body: json
        property: json[1].name
        is: "bar"
      - body: json
        property: json
        length: 2
```

Example 2:

```
{
  "items": 
    [
      "foo",
      "bar"
    ]
}
```

```  
- title: get list of items
    get: /items/
    assert:
      - status: 200
      - body: json
        property: json.items[0]
        is: "foo"
      - body: json
        property: json.items[1]
        is: "bar"
      - body: json
        property: json.items
        length: 2
```
